Grid[{
  {"in1", "in2", "result", "how", "fullform", "description"},
  {"{a,b,c,d,e,f}", "", "d", "in1[[4]]", "Part[in1,4]", ""},
  {"{a,b,c,d,e,f}", "", "a", "in1[[1]] \nFirst[in1]", "Part[in1,4]", 
   ""},
  {"{a,b,c,d,e,f}", "", "f", "in1[[-1]] \nLast[in1]", "Part[in1,-1]", 
   ""},
  {"{a,b,c,d,e,f}", "", "{b,c,d}", "in1[[2;;4]]", "Take[in1,{2,4}]", 
   "Take elements 2 through 4"},
  {"{a,b,c,d,e,f}", "", "{a,b,c,d}", "in1[[;;4]]", "Take[in1,4]", 
   "Take the first 4 elements"},
  {"{a,b,c,d,e,f}", "", "{d,e,f}", "in1[[-3;;]]", "Take[in1,-3]", 
   "Take the last 3 elements"},
  {"{a,b,c,d,e,f}", "", "{b,c,d,e}", "in1[[2;;-2]]", 
   "Take[in1,{2,-2}]", 
   "Take elements from the second to the second-to-last"},
  {"{a,b,c,d,e,f}", "", "{a,c,e}", "in1[[1;;-1;;2]] \nin1[[{1,3,5}]]",
    "Take[in1,{1,-1,2}]", "Take every other element"},
  {"{a,b,c,d,e,f}", "", "{f,e,d,c,b,a}", "in1[[-1;;1;;-1]]", 
   "Take[in1,{-1,1,-1}] \nReverse[in1]", "Reverse the list"},
  {"{a,b,c,d,e,f}", "", "{b,c,d,e,f}", "in1[[2;;]]", 
   "Rest[in1] \nDrop[in1,1]", 
   "Give the list with the first element removed"},
  {"{a,b,c,d,e,f}", "", "{a,b,c,d,e}", "in1[[;;-2]]", 
   "Most[in1] \nDrop[in1,-1]", 
   "Give the list with the last element removed"},
  {"{a,b,c,d,e,f}", "", "a+b+c+d+e+f", "Plus@@in1 \nTotal@in1", 
   "Total[in1]", ""},
  {"{a,b,c,d,e,f}", "", "a*b*c*d*e*f", "Times@@in1", "", ""},
  {"{a,b,c,d,e,f}", "", "{a,a+b,a+b+c,a+b+c+d,a+b+c+d+e,a+b+c+d+e+f}",
    "Accumulate@@in1 \nin1//Accumulate \nRest[FoldList[Plus,0,in1]]", 
   "Accumulate[in1]", 
   "Accumulate is equivalent to a particular case of FoldList"},
  {"{{a,b},{c,d},{e,f}}", "", "{{a,b},{a+c,b+d},{a+c+e,b+d+f}}", 
   "Accumulate@@in1 \nin1//Accumulate", "Accumulate[in1]", ""},
  {"{a,b,c}", "x", "{a,x,b,x,c}", "Riffle[in1,x]", "", ""},
  {"{a,b,c}", "x", "{a,b,c,x,x}", "PadRight[in1,3+2,x]", "", ""},
  {"{a,b,c}", "x", "{x,x,a,b,c}", "PadLeft[in1,2+3,x]", "", ""},
  {"{a,b,c,d,e,f}", "", 
   "{\!\(\*FractionBox[\(a + b\), \(2\)]\),\!\(\*FractionBox[\(b + \
c\), \(2\)]\),\!\(\*FractionBox[\(c + d\), \
\(2\)]\),\!\(\*FractionBox[\(d + e\), \(2\)]\),\!\(\*FractionBox[\(e \
+ f\), \(2\)]\)}", "MovingAverage[in1,2]", "", ""},
  {"{a,b,c,d,e,f}", "", 
   "{\!\(\*FractionBox[\(a\), \(3\)]\)+\!\(\*FractionBox[\(2\\\ b\), \
\(3\)]\),\!\(\*FractionBox[\(b\), \(3\)]\)+\!\(\*FractionBox[\(2\\\ c\
\), \(3\)]\),\!\(\*FractionBox[\(c\), \
\(3\)]\)+\!\(\*FractionBox[\(2\\\ d\), \(3\)]\),\!\(\*FractionBox[\(d\
\), \(3\)]\)+\!\(\*FractionBox[\(2\\\ e\), \
\(3\)]\),\!\(\*FractionBox[\(e\), \(3\)]\)+\!\(\*FractionBox[\(2\\\ f\
\), \(3\)]\)}", "MovingAverage[in1,{1,2}]", "", 
   "Compute weighted moving averages"},
  {"{a,b,c,d,e,f}", "", "{{a},{b},{c},{d},{e},{f}}", 
   "Tuples[in1,1] \nSplit[in1] \nPartition[in1,2] \n{#}&/@in1", "", 
   "Tuples is the fastest one. Split could produce wrong result for \
same elements Split[{1,1,2,2,3,3,4}]=={{1,1},{2,2},{3,3},{4}}"},
  {"{a,b,c,d,e,f}", "", "{{a,b},{c,d},{e,f}}", "Partition[in1,2]", "",
    "Partition into sublists of length 2"},
  {"{a,b,c,d,e,f}", "", "{{a,b,c},{d,e,f}}", "Partition[in1,3]", "", 
   "Partition into sublists of length 3"},
  {"{a,b,c,d,e,f}", "", "{{a,b,c},{b,c,d},{c,d,e},{d,e,f}}", 
   "Partition[{a,b,c,d,e,f},3,1]", "", 
   "Partition into sublists of length 3 with offset 1"},
  {"{a,a,b,a,c,b,a}", "", "{{a,4},{b,2},{c,1}}", 
   "Tally@in1 \nin1//Tally", "Tally[in1]", 
   "tallies the elements in list, listing all distinct elements \
together with their multiplicities."},
  {"{b,a,c,b,a,c,b,a}", "", "{b,a}", "Commonest@in1", 
   "Commonest[in1]", "Elements with highest frequencies"},
  {"{a,b,c}", "{d,e,f}", "{a,b,c,d,e,f}", 
   "Join@@{in1,in2} \nin1~Join~in2", 
   "Join[in1,in2] \nInfix[Join[in1,in2]]", ""},
  {"{a,b,c}", "{c,d,e}", "{a,b,c,d,e}", 
   "Union@@{in1,in2} \nin1~Union~in2", 
   "Union[in1,in2] \nInfix[Union[in1,in2]]", ""},
  {"{a,b,c}", "{c,d,e}", "{c}", 
   "Intersection@@{in1,in2} \nin1~Intersection~in2", 
   "Intersection[in1,in2] \nInfix[Intersection[in1,in2]]", ""},
  {"{a,b,c}", "{d,e,f}", "{a,d,b,e,c,f}", "Riffle[in1,in2]", "", ""},
  {"{a,b,c}", "{d,e,f}", "a d+b e+c f", "in1.in2", "Dot[in1,in2]", ""},
  {"{a,b,c}", "{d,e,f}", "{a+d,b+e,c+f}", "in1+in2", "Plus[in1,in2]", 
   ""},
  {"{a,b,c}", "{d,e,f}", "{a d,b e,c f}", "in1*in2", "Times[in1,in2]",
    ""},
  {"{a,b,c}", "{d,e,f}", "{a^d,b^e,c^f}", "in1^in2", "Power[in1,in2]",
    ""},
  {"{a,b,c}", "{d,e,f}", "{{a,d},{b,e},{c,f}}", 
   "Transpose[{in1,in2}]", "", ""},
  {"{{a,b,c},{d,e},{f}}", "", "{{a,b,c},{0,d,e},{0,0,f}}", 
   "PadLeft[in1]", "", ""},
  {"{a,b,c}", "{d,e,f}", "{a->d,b->e,c->f}", "Thread[in1->in2]", "", 
   ""}
  
  }, Frame -> All, Alignment -> Left]
